version: '3.9'

services:

#  golang:
#    image: golang:alpine3.18
#    volumes:
#      - ./:/usr/src/myApp
#    working_dir:
#      /usr/src/myApp
#    entrypoint: go run main.go
#    ports:
#      - 8080:8080

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=base
    volumes:
      - ./docker/database:/var/lib/mysql
    ports:
      - 33061:3306
    restart: always

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 2025:1025
      - 9025:8025


