version: '3.9'

services:

  golang:
    image: golang:alpine3.18
    volumes:
      - ./:/usr/src/myApp
    working_dir:
      /usr/src/myApp

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=base
    volumes:
      - ./docker/database:/var/lib/mysql
    ports:
      - 33061:3306
    restart: always

#  mysql_test:
#    image: mysql:8.0
#    environment:
#      - MYSQL_ROOT_PASSWORD=test
#      - MYSQL_DATABASE=base_test
#    volumes:
#      - ./docker/database_test:/var/lib/mysql
#    ports:
#      - 33062:3306
#    restart: always

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 2025:1025
      - 9025:8025
#
#  golang:
#    build:
#      context: ./
#      dockerfile: ./DockerFile
#    container_name: golang
#    volumes:
#      - ./:/usr/src/app
#    ports:
#      - 8081:8081
#    restart: always

